### ISSUE TITLE
how to run and tail stdout

### ISSUE THREAD

**Issue by ShylockGou** [connexio-labs/docker-alpine-nginx#1]
how to run and tail stdout

**Comment by johnallen3d** [comment]
If you run the container in the foreground the logs should be available in stdout as normal. You'll need to expose a port if you'd like to hit the container externally. Something like this should do.

```sh
❯ docker run -p 80:80 connexiolabs/alpine-nginx:1.7.11
```

<img width="723" alt="alpine-stdout" src="https://cloud.githubusercontent.com/assets/184915/9568099/6fe57226-4f0e-11e5-874d-4b9dd9455d2a.png">

**Comment by ShylockGou** [comment]
by the way ,your terminal is so beautiful,what kinds of font you used and ?and the split is the tmux? tks

**Comment by johnallen3d** [comment]
Thanks, I'm using iTerm 2 (the splits) with 14pt DejaVu Sans Mono Bold for font and the [Dracula](http://zenorocha.github.io/dracula-theme/iterm/) theme. In addition I'm using zsh/prezto.
